name: Go

on:
  push:

env:
  GH_REPO_NAME: ${{ github.event.repository.name }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        token: ${{ github.token }}

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      run: go test -cover -race -v ./...
